function showText(elem){
    document.getElementById("1");
    elem.innerHTML=("<center>To solve the problem of soul-destroying traffic, roads must go 3D, which means either flying cars or tunnels. Unlike flying cars, tunnels are weatherproof, out of sight and won't fall on your head. A large network of tunnels many levels deep would fix congestion in any city, no matter how large it grew (just keep adding levels). The key to making this work is increasing tunneling speed and dropping costs by a factor of 10 or more – this is the goal of The Boring Company. Fast to dig, low cost tunnels would also make Hyperloop adoption viable and enable rapid transit across densely populated regions, enabling travel from New York to Washington DC in less than 30 minutes.</center>");
    elem.classList.toggle("hello");
}
function showText2(elem){
    document.getElementById("2");
    elem.innerHTML=("<center>A Hyperloop is a proposed mode of passenger and/or freight transportation, first used to describe an open-source vactrain design released by a joint team from Tesla and SpaceX. Drawing heavily from Robert Goddard's vactrain, a hyperloop comprises a sealed tube or system of tubes through which a pod may travel free of air resistance or friction conveying people or objects at high speed while being very efficient. Elon Musks version of the concept, first publicly mentioned in 2012, incorporates reduced-pressure tubes in which pressurized capsules ride on air bearings driven by linear induction motors and air compressors. The Hyperloop Alpha concept was first published in August 2013, proposing and examining a route running from the Los Angeles region to the San Francisco Bay Area roughly following the Interstate 5 corridor. The paper conceived of a hyperloop system that would propel passengers along the 350-mile (560 km) route at an average speed of around 600 mph (970 km/h), with a top speed of 760 mph (1,200 km/h), allowing for a travel time of 35 minutes, which is considerably faster than current rail or air travel times. Preliminary cost estimates for this LA–SF suggested route were included in the white paper—US$6 billion for a passenger-only version, and US$7.5 billion for a somewhat larger-diameter version transporting passengers and vehicles—although transportation analysts had doubts that the system could be constructed on that budget; some analysts claimed that the Hyperloop would be several billion dollars overbudget, taking into consideration construction, development and operation costs.</center>");
    elem.classList.toggle("white");
}
function showText3(elem){
    document.getElementById("3");
    elem.innerHTML=("<center>Space Exploration Technologies Corp., doing business as SpaceX, is an American aerospace manufacturer and space transport services company headquartered in Hawthorne, California. It was founded in 2002 by entrepreneur Elon Musk with the goal of reducing space transportation costs and enabling the colonization of Mars.[8] SpaceX has since developed the Falcon launch vehicle family and the Dragon spacecraft family, which both currently deliver payloads into Earth orbit. SpaceXs achievements include the first privately funded liquid-propellant rocket to reach orbit (Falcon 1 in 2008); the first privately funded company to successfully launch, orbit, and recover a spacecraft (Dragon in 2010); the first private company to send a spacecraft to the International Space Station (Dragon in 2012); the first propulsive landing for an orbital rocket (Falcon 9 in 2015); and the first reuse of an orbital rocket (Falcon 9 in 2017). As of March 2017, SpaceX has since flown ten missions to the International Space Station (ISS) under a cargo resupply contract. NASA also awarded SpaceX a further development contract in 2011 to develop and demonstrate a human-rated Dragon, which would be used to transport astronauts to the ISS and return them safely to Earth.</center>");
    elem.classList.toggle("white");
}
function showText4(elem){
    document.getElementById("4");
    elem.innerHTML=("<center>Tesla, Inc. (formerly Tesla Motors) is an American automaker, energy storage company, and solar panel manufacturer based in Palo Alto, California. Founded in 2003, the company specializes in electric cars, lithium-ion battery energy storage, and residential photovoltaic panels (through the subsidiary company SolarCity). The additional products Tesla sells include the Tesla Powerwall and Powerpack batteries, solar panels and solar roof tiles. CEO Elon Musk said that he envisions Tesla as a technology company and independent automaker, aimed at eventually offering electric cars at prices affordable to the average consumer. The company was named after the Serbian-American electrical engineer and physicist Nikola Tesla by company co-founders Martin Eberhard and Marc Tarpenning.The company's Model S was the world's best-selling plug-in electric car in 2015 and 2016. Global sales of the Model S reached 150,000 units in November 2016. In September 2015 the company released its Model X, a crossover SUV. The Model 3 was released in July 2017. Tesla global sales passed 250,000 units in September 2017.</center>      ");
}
function playSound(elem){
	document.getElementById("elon").play();
}
